v2.0
Fishy-Fishes/yt-blocker pull request #6
Opened 2021-10-14 12:57 UTC by XcodeBoi

Improved latency of content being hidden and reworked how script is called.

Overall simplified.

If you have a moment to look at it, I would greatly appreciate feedback.

If you have nothing to comment thats OK to.

2021-10-14 13:09 UTC, liam-bh commented on injection.js
> +const customCSS = ".ytd-rich-grid-renderer, .ytd-item-section-renderer, .ytd-compact-video-renderer { opacity: 0; pointer-events: none; }";
`.ytd-item-section-renderer` removes the comments section as well and will need to be changed.

Though considering the point of this extension is to reduce unproductive time on youtube it's arguably a good thing.

2021-10-14 23:57 UTC, SleepySwords commented on injection.js
> +const customCSS = ".ytd-rich-grid-renderer, .ytd-item-section-renderer, .ytd-compact-video-renderer { opacity: 0; pointer-events: none; }";
Could be a setting. Clicking on the extension would result in a pop-up menu like other extenions.

2021-10-15 00:13 UTC, SleepySwords requested changes, later dismissed
LGTM! Just a two nitpicks.

2021-10-15 00:13 UTC, SleepySwords commented on injection.js
> +	} else {
Another nitpick, but you can combine this with the above else to form an `else if`

2021-10-15 00:13 UTC, SleepySwords commented on injection.js
> +function URLchecker() {
Nitpick
The name of this function should probably be something like `updateStyle` or `checkAndUpdateStyle`.
I think it gives just that little more information.

2021-10-15 00:33 UTC, SleepySwords commented
Oh, Brave just crashes when I tried to use it on Mac OS.

2021-10-15 00:37 UTC, XcodeBoi commented on injection.js
> +const customCSS = ".ytd-rich-grid-renderer, .ytd-item-section-renderer, .ytd-compact-video-renderer { opacity: 0; pointer-events: none; }";
Yeah if I feel like it actually becomes a problem then I'll add that in. V2.1 even.

2021-10-15 00:47 UTC, liam-bh commented
I had huge issues with my browser crashing and then being unable to open when it errored, which was to do with issues in error logging. Chrome worked fine while Vivaldi did not.

The whole browser crashing shouldn't occur no matter what - errors should just be logged in chrome://extentions

So weird things going on I guess it isn't as stable as I believed.

Are you able to retrieve the error from Brave?

2021-10-15 00:53 UTC, SleepySwords commented
Yeah, it's definitely weird, it works on Chrome for me as well.

I'll try to get those errors.

2021-10-15 02:14 UTC, SleepySwords commented
Weirdly enough the errors I get is this
```
[1015/130753.828913:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffeef214000, 0x2000): (os/kern) invalid address (1)
[1015/130754.846829:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5)
fish: Job 1, '/Applications/Brave\ Browser.ap…' terminated by signal SIGILL (Illegal instruction)
```

It definitely looks like it's a Chromium/Brave issue.

2021-10-15 02:14 UTC, SleepySwords approved these changes

2021-10-15 06:19 UTC, liam-bh commented
Yeah for sure.

2021-10-15 06:19 UTC, merged